//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartonPriceEstimator
    {
        public int carton_id { get; set; }
        public string trade { get; set; }
        public string companyName { get; set; }
        public string dimension { get; set; }
        public int quantity { get; set; }
        public double unitCost { get; set; }
        public string material { get; set; }
    }
}
