//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quotation
    {
        public int quotation_id { get; set; }
        public string trade { get; set; }
        public string company { get; set; }
        public string material { get; set; }
        public string dimension { get; set; }
        public int quantity { get; set; }
        public double unit_cost { get; set; }
        public int buyer_id { get; set; }
        public int seller_id { get; set; }
        public string buyer_name { get; set; }
        public string seller_name { get; set; }
    
        public virtual buyer buyer { get; set; }
        public virtual seller seller { get; set; }
    }
}
